import { ReceiptIcon as ExpensesIcon, FileBarChart } from "lucide-react"
import { Button } from "@/components/ui/button"

export default function ExpensesReportPage() {
  return (
    <div>
      <div className="bg-red-600 text-white p-4 rounded-t-lg flex justify-between items-center">
        <h1 className="text-xl font-medium flex items-center">
          <ExpensesIcon className="h-5 w-5 mr-2" />
          Expenses Reports
        </h1>
        <Button className="bg-white text-red-600 hover:bg-gray-100">
          <FileBarChart className="h-4 w-4 mr-1" /> Generate Report
        </Button>
      </div>

      <div className="bg-white rounded-b-lg p-6 shadow-md">
        <div className="mb-6">
          <h2 className="text-lg font-medium mb-4">Available Expense Reports</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            <div className="border rounded-lg p-4 hover:shadow-md transition-shadow">
              <h3 className="font-medium mb-2">Expense by Category</h3>
              <p className="text-sm text-gray-600 mb-4">Breakdown of expenses by category for a specific period.</p>
              <Button variant="outline" size="sm" className="w-full">
                View Report
              </Button>
            </div>

            <div className="border rounded-lg p-4 hover:shadow-md transition-shadow">
              <h3 className="font-medium mb-2">Expense by Department</h3>
              <p className="text-sm text-gray-600 mb-4">Breakdown of expenses by department for a specific period.</p>
              <Button variant="outline" size="sm" className="w-full">
                View Report
              </Button>
            </div>

            <div className="border rounded-lg p-4 hover:shadow-md transition-shadow">
              <h3 className="font-medium mb-2">Monthly Expense Trend</h3>
              <p className="text-sm text-gray-600 mb-4">Monthly expense trends over time.</p>
              <Button variant="outline" size="sm" className="w-full">
                View Report
              </Button>
            </div>

            <div className="border rounded-lg p-4 hover:shadow-md transition-shadow">
              <h3 className="font-medium mb-2">Budget vs. Actual</h3>
              <p className="text-sm text-gray-600 mb-4">Comparison of budgeted expenses against actual expenses.</p>
              <Button variant="outline" size="sm" className="w-full">
                View Report
              </Button>
            </div>

            <div className="border rounded-lg p-4 hover:shadow-md transition-shadow">
              <h3 className="font-medium mb-2">Expense Analysis</h3>
              <p className="text-sm text-gray-600 mb-4">Detailed analysis of expense patterns and anomalies.</p>
              <Button variant="outline" size="sm" className="w-full">
                View Report
              </Button>
            </div>
          </div>
        </div>

        <div className="border-t pt-6">
          <h2 className="text-lg font-medium mb-4">Recent Reports</h2>
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th
                    scope="col"
                    className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Report Name
                  </th>
                  <th
                    scope="col"
                    className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Generated Date
                  </th>
                  <th
                    scope="col"
                    className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Period
                  </th>
                  <th
                    scope="col"
                    className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Generated By
                  </th>
                  <th
                    scope="col"
                    className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {[1, 2, 3, 4, 5].map((item) => (
                  <tr key={item} className="hover:bg-gray-50">
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="text-sm font-medium text-gray-900">
                        {
                          [
                            "Expense by Category",
                            "Expense by Department",
                            "Monthly Expense Trend",
                            "Budget vs. Actual",
                            "Expense Analysis",
                          ][item - 1]
                        }
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {["31/03/2025", "25/03/2025", "20/03/2025", "15/03/2025", "10/03/2025"][item - 1]}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {["Q1 2025", "March 2025", "Jan-Mar 2025", "Q1 2025", "February 2025"][item - 1]}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {["Finance Manager", "Department Head", "Accountant", "Finance Manager", "Accountant"][item - 1]}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                      <a href="#" className="text-red-600 hover:text-red-900 mr-3">
                        Download
                      </a>
                      <a href="#" className="text-gray-600 hover:text-gray-900">
                        View
                      </a>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  )
}
