import { PackageIcon, FileBarChart } from "lucide-react"
import { Button } from "@/components/ui/button"

export default function InventoryReportPage() {
  return (
    <div>
      <div className="bg-red-600 text-white p-4 rounded-t-lg flex justify-between items-center">
        <h1 className="text-xl font-medium flex items-center">
          <PackageIcon className="h-5 w-5 mr-2" />
          Inventory Reports
        </h1>
        <Button className="bg-white text-red-600 hover:bg-gray-100">
          <FileBarChart className="h-4 w-4 mr-1" /> Generate Report
        </Button>
      </div>

      <div className="bg-white rounded-b-lg p-6 shadow-md">
        <div className="mb-6">
          <h2 className="text-lg font-medium mb-4">Available Inventory Reports</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            <div className="border rounded-lg p-4 hover:shadow-md transition-shadow">
              <h3 className="font-medium mb-2">Stock Level Report</h3>
              <p className="text-sm text-gray-600 mb-4">Current inventory levels across all warehouses.</p>
              <Button variant="outline" size="sm" className="w-full">
                View Report
              </Button>
            </div>

            <div className="border rounded-lg p-4 hover:shadow-md transition-shadow">
              <h3 className="font-medium mb-2">Stock Movement</h3>
              <p className="text-sm text-gray-600 mb-4">Inventory movement (in/out) for a specific period.</p>
              <Button variant="outline" size="sm" className="w-full">
                View Report
              </Button>
            </div>

            <div className="border rounded-lg p-4 hover:shadow-md transition-shadow">
              <h3 className="font-medium mb-2">Inventory Valuation</h3>
              <p className="text-sm text-gray-600 mb-4">Financial valuation of current inventory.</p>
              <Button variant="outline" size="sm" className="w-full">
                View Report
              </Button>
            </div>

            <div className="border rounded-lg p-4 hover:shadow-md transition-shadow">
              <h3 className="font-medium mb-2">Low Stock Alert</h3>
              <p className="text-sm text-gray-600 mb-4">Items with stock levels below reorder point.</p>
              <Button variant="outline" size="sm" className="w-full">
                View Report
              </Button>
            </div>

            <div className="border rounded-lg p-4 hover:shadow-md transition-shadow">
              <h3 className="font-medium mb-2">Stock Aging</h3>
              <p className="text-sm text-gray-600 mb-4">Analysis of how long items have been in inventory.</p>
              <Button variant="outline" size="sm" className="w-full">
                View Report
              </Button>
            </div>
          </div>
        </div>

        <div className="border-t pt-6">
          <h2 className="text-lg font-medium mb-4">Recent Reports</h2>
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th
                    scope="col"
                    className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Report Name
                  </th>
                  <th
                    scope="col"
                    className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Generated Date
                  </th>
                  <th
                    scope="col"
                    className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Warehouse
                  </th>
                  <th
                    scope="col"
                    className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Generated By
                  </th>
                  <th
                    scope="col"
                    className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {[1, 2, 3, 4, 5].map((item) => (
                  <tr key={item} className="hover:bg-gray-50">
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="text-sm font-medium text-gray-900">
                        {
                          [
                            "Stock Level Report",
                            "Stock Movement",
                            "Inventory Valuation",
                            "Low Stock Alert",
                            "Stock Aging",
                          ][item - 1]
                        }
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {["31/03/2025", "25/03/2025", "20/03/2025", "15/03/2025", "10/03/2025"][item - 1]}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {
                        ["All Warehouses", "Main Warehouse", "All Warehouses", "Branch 1 Store", "All Warehouses"][
                          item - 1
                        ]
                      }
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {
                        [
                          "Inventory Manager",
                          "Store Supervisor",
                          "Inventory Manager",
                          "Store Clerk",
                          "Inventory Manager",
                        ][item - 1]
                      }
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                      <a href="#" className="text-red-600 hover:text-red-900 mr-3">
                        Download
                      </a>
                      <a href="#" className="text-gray-600 hover:text-gray-900">
                        View
                      </a>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  )
}
