import { FileTextIcon as FileText2, FileBarChart } from "lucide-react"
import { Button } from "@/components/ui/button"

export default function FinancialStatementPage() {
  return (
    <div>
      <div className="bg-red-600 text-white p-4 rounded-t-lg flex justify-between items-center">
        <h1 className="text-xl font-medium flex items-center">
          <FileText2 className="h-5 w-5 mr-2" />
          Financial Statement Reports
        </h1>
        <Button className="bg-white text-red-600 hover:bg-gray-100">
          <FileBarChart className="h-4 w-4 mr-1" /> Generate Report
        </Button>
      </div>

      <div className="bg-white rounded-b-lg p-6 shadow-md">
        <div className="mb-6">
          <h2 className="text-lg font-medium mb-4">Available Financial Statements</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            <div className="border rounded-lg p-4 hover:shadow-md transition-shadow">
              <h3 className="font-medium mb-2">Income Statement</h3>
              <p className="text-sm text-gray-600 mb-4">
                Statement of revenue, expenses, and profit/loss for a specific period.
              </p>
              <Button variant="outline" size="sm" className="w-full">
                View Report
              </Button>
            </div>

            <div className="border rounded-lg p-4 hover:shadow-md transition-shadow">
              <h3 className="font-medium mb-2">Balance Sheet</h3>
              <p className="text-sm text-gray-600 mb-4">
                Statement of assets, liabilities, and equity at a specific point in time.
              </p>
              <Button variant="outline" size="sm" className="w-full">
                View Report
              </Button>
            </div>

            <div className="border rounded-lg p-4 hover:shadow-md transition-shadow">
              <h3 className="font-medium mb-2">Cash Flow Statement</h3>
              <p className="text-sm text-gray-600 mb-4">
                Statement of cash inflows and outflows for a specific period.
              </p>
              <Button variant="outline" size="sm" className="w-full">
                View Report
              </Button>
            </div>

            <div className="border rounded-lg p-4 hover:shadow-md transition-shadow">
              <h3 className="font-medium mb-2">Profit & Loss</h3>
              <p className="text-sm text-gray-600 mb-4">Detailed breakdown of revenue and expenses.</p>
              <Button variant="outline" size="sm" className="w-full">
                View Report
              </Button>
            </div>

            <div className="border rounded-lg p-4 hover:shadow-md transition-shadow">
              <h3 className="font-medium mb-2">Financial Ratios</h3>
              <p className="text-sm text-gray-600 mb-4">Key financial ratios and performance indicators.</p>
              <Button variant="outline" size="sm" className="w-full">
                View Report
              </Button>
            </div>
          </div>
        </div>

        <div className="border-t pt-6">
          <h2 className="text-lg font-medium mb-4">Recent Reports</h2>
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th
                    scope="col"
                    className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Report Name
                  </th>
                  <th
                    scope="col"
                    className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Generated Date
                  </th>
                  <th
                    scope="col"
                    className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Period
                  </th>
                  <th
                    scope="col"
                    className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Generated By
                  </th>
                  <th
                    scope="col"
                    className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {[1, 2, 3, 4, 5].map((item) => (
                  <tr key={item} className="hover:bg-gray-50">
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="text-sm font-medium text-gray-900">
                        {
                          [
                            "Income Statement",
                            "Balance Sheet",
                            "Cash Flow Statement",
                            "Profit & Loss",
                            "Financial Ratios",
                          ][item - 1]
                        }
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {["31/03/2025", "31/03/2025", "28/02/2025", "31/01/2025", "31/12/2024"][item - 1]}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {["Q1 2025", "Q1 2025", "February 2025", "January 2025", "Q4 2024"][item - 1]}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {["Finance Manager", "Finance Manager", "Accountant", "Accountant", "Finance Manager"][item - 1]}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                      <a href="#" className="text-red-600 hover:text-red-900 mr-3">
                        Download
                      </a>
                      <a href="#" className="text-gray-600 hover:text-gray-900">
                        View
                      </a>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  )
}
